### PR TITLE
Add button to directly load sample data

### PR DESCRIPTION
**Pull request by pverscha**
This PR introduces a new button that allows the user to directly load the sample data into the text areas on the analysis page. See the following screenshot for more details:

image

### CODE REVIEW

**Review by rababerladuseladim — APPROVED** [review]
I am entirely unable to judge these changes but I am sure they work as supposed :-P

**Comment by pverscha** [comment]
@rababerladuseladim I just wanted to ask your approval here to make sure the new button works as you expected :) (meaning that the GUI looks a bit to what you had in mind) :) There aren't a lot of changes to the code itself

**Comment by rababerladuseladim** [comment]
Damn, I should have paid better attention. My apologies. What do you think about a single button to load example data for both sets? And calling it "example data" might make it easier to differentiate it from user provided sample data.

**Comment by pverscha** [comment]
@rababerladuseladim No worries! I'll add one button on top and remove the current buttons. I will make a new PR and tag you once I'm done :)

**Pull request merged**
